language: python
python:
 - "3.7"
script:
 - python -m unittest tests.testMasseyMethod
 - python -m unittest tests.testDataCollection
 - python -m unittest tests.testDriver
after_success:
 - codecov # submit coverage
