language: python
python:
 - "3.7"
script:
 - python -m unittest src.tests.testMasseyMethod
 - python -m unittest src.tests.testDataCollection
 - python -m unittest src.tests.testDriver

after_success:
 - coverage run -m unittest discover
 - coverage report > src.tests.codecov.txt
